before_script:
    - apt-get update -y
    - apt-get install -y libssl-dev build-essential wget
    - wget -qO- https://raw.githubusercontent.com/creationix/nvm/v0.29.0/install.sh | bash
    - source /root/.bashrc
    - nvm install node
    - nvm use node
    - npm install && npm install -g mocha

test:
    script:
        - npm test



job_deploy:
  stage: deploy
  tags: delpoyServer1
  script:
    -  npm install &&  forever restartall
